<?php Tag::css('galeria')?>
<div class="contenedor">
    <div class="contenido">
		<section class="left">
			<article class="album">
				<?php
                    if ( $album->total == 0)
                        print "<td colspan='6' class='strong font-large font-center'>Galería Vacía</td>";
                    else
                    foreach ($album->items as $fila):
                    ?>
                    <article class="album">
						<h3><?php echo $fila->nombre.'('.$fila->cantidad.')'; ?></h3>
						<?php echo Html::img('dcm/galeria/'.$fila->ruta.$fila->nombre_ruta, null, "width='80px' height='60px'"); ?>
						<p>
							<?php echo 'Publicado por: '.$fila->login; ?>
							<br/>
							<?php echo ExtDate::getHowLong($fila->fecha_creacion_at.' '.$fila->hora_creacion_at);?>
						</p>
					</article>
                    <?php endforeach;?>
		</section>
		<!-- <section class="right"></section> -->
	</div>
</div>



