<?php View::partial('mensaje'); ?>

<div class="contenido">        
    <div class="left large"><h1 class="text-shadow"><?php echo ucfirst($clasificacion).'s'; ?><span><?php if(isset($busqueda)) { echo "Resultado de la búsqueda para \"$busqueda\""; }; ?></span> </h1></div>
    <div class="right small">
        <?php View::partial('admin/form_busqueda', array('action'=>'')); ?>
    </div>
    <div class="clr"></div>
    
    <div class="left small">
        <div class="box ui-corner-all ui-widget-content" id="nueva-etiqueta">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Nueva <?php echo $clasificacion; ?></h3></div>
            <div class="box-contenido box-form">
                <?php echo ExtForm::open('dc-admin/'.Filter::get($clasificacion,'acento').'/registrar/', 'post', '', true); ?>
                <ul>
                    <li>
                        <label for="taxonomia_nombre" class="desc">Nombre<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('taxonomia.nombre', array('class'=>'texto full'), null, '', true, true); ?>
                            <div class="input-info">Nombre como se mostrará en el blog.<br />Ejemplo: Tutorial</div>
                        </div>
                    </li>
                    <li>
                        <label for="taxonomia_url" class="desc">Slug</label>
                        <div>
                            <?php echo ExtForm::text('taxonomia.url', array('class'=>'slug full'), null, '', false, true); ?>
                            <div class="input-info">El "slug" es la versión amigable de la url.<br />Ejemplo: mis-tutoriales</div>
                        </div>
                        <div>
                            <?php echo ExtForm::hidden('taxonomia.tipo', '', $tipo); ?>
                        </div>
                    </li>
                    <li>
                        <div>
                            <?php echo SecurityKey::generateKey(); ?>
                        </div>
                    </li>
                </ul>
                 <div class="box-botones">
                    <div class="left medium">
                        <span><?php echo ExtForm::submit('Guardar'); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>
                <?php echo ExtForm::close(); ?>
            </div>
        </div>
    </div>
    
    <div class="right large">
        <div class="box ui-corner-all ui-widget-content" id="listado-etiqueta">
            <table class="data-grid" cellspacing="0">
                <thead class="ui-state-default ui-corner-tl ui-corner-tr">
                    <tr class="text-shadow">
                        <th class="columna-check">&nbsp</th>
                        <th class="taxonomia-nombre">Nombre</th>
                        <th class="taxonomia-slug">Slug</th>
                        <th class="taxonomia-post">Post</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($taxonomia as $fila) : ?>
                    <?php $validKey = md5($fila->id.$ipKey.$expKey.Filter::get($clasificacion,'acento')); ?>
                    <tr>
                        <th>&nbsp;</th>
                        <td class="font-left"><span class="strong"><?php echo $fila->nombre; ?></span><br/>
                            <div class="row-actions font-small">
                                <span class="row-action-edit"><?php echo Html::link("dc-admin/".Filter::get($clasificacion,'acento')."/editar/$fila->id/key/$validKey/",'Editar');?> | </span>
                                <span class="row-action-delete"><?php echo Html::link("dc-admin/".Filter::get($clasificacion,'acento')."/eliminar/$fila->id/key/$validKey/",'Eliminar');?></span>
                            </div>
                        </td>
                        <td class="font-left"><?php echo $fila->url;?></td>
                        <td class="font-center strong"><?php echo Html::link("dc-admin/post/listar/todos/".Filter::get($clasificacion,'acento')."/$fila->url/", $fila->total_post);?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="break"></div>
</div>
    
<!-- Alertas -->
<script type="text/javascript">
    var link_action;
    $('a','.row-action-delete').click(function(event){ event.preventDefault(); link_action = $(this).attr('href'); $('#eliminar-taxonomia').dialog('open'); });
    $(function() { $("#eliminar-taxonomia").dialog({ autoOpen: false, width: 400, height:155, modal: true, buttons: { 'Cancelar': function() { $(this).dialog('close'); } ,'Aceptar': function() { location.href = link_action; } } }); });
</script>
<div id="eliminar-taxonomia" title="<?php echo APP_NAME; ?>" class="confirm-dialog">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseas borrar permantentemente esta <?php echo Filter::get($clasificacion,'acento'); ?>?. </p>
</div>
<script type="text/javascript">
    $(function() {
        $('#limpiar').click(function(){ document.getElementById('formulario').reset();limpiar_err();});
        $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('tr-hover'); },function() {});
    });    
 </script>
