<div id="contenedor-cabecera">
    <div id="cabecera">
      <div id="logo"><a href="<?php echo PUBLIC_PATH; ?>"><?php echo Html::img('logo_negro.png', 'Logo', array('width'=>'349', 'height'=>'98', 'border'=>'0') ); ?></a> </div>
      <div id="social-media">
        <p><a href="#" class="thre"><?php echo Html::img('pagina/spacer.gif', 'social', array('width'=>'24', 'height'=>'23', 'border'=>'0') ); ?></a> <a href="#" class="sek"><?php echo Html::img('pagina/spacer.gif', 'social', array('width'=>'24', 'height'=>'23', 'border'=>'0') ); ?></a> <a href="#" class="first"><?php echo Html::img('pagina/spacer.gif', 'social', array('width'=>'24', 'height'=>'23', 'border'=>'0') ); ?></a> </p>
      </div>

    </div>
    <div class="clr"></div>
</div>