<div id="contenedor-extra">
    <div id="extra">
        <div class="left">
            <h3>La empresa</h3>
            <ul>
                <li><?php echo Html::link('empresa/#descripcion', 'Quienes somos');?></li>
                <li><?php echo Html::link('empresa/#mision', 'Misión');?></li>
                <li><?php echo Html::link('empresa/#vision', 'Visión');?></li>
                <li><?php echo Html::link('empresa/#valores', 'Valores');?></li>
            </ul>
        </div>
        <div class="left">
            <h3>Sercivios</h3>
            <ul>
                <li><a href="#">First Service</a></li>
                <li><a href="#">Second Service</a></li>
                <li><a href="#">Another Service</a></li>
                <li><a href="#">A Fourth Service</a></li>
            </ul>
        </div>
        <div class="clr"></div>
    </div>
    <div class="clr"></div>
</div>
