<div id="contenedor-navegador">
    <div id="navegador">
        <div id="menu">
            <ul>
                <li><a href="<?php echo PUBLIC_PATH."principal/";?>" <?php if(isset($principal)) echo "class=\"activo\"";?> ><span>Principal</span></a></li>
                <li><a href="<?php echo PUBLIC_PATH."empresa/";?>" <?php if(isset($empresa)) echo "class=\"activo\"";?> ><span>Empresa</span></a></li>
                <li><a href="<?php echo PUBLIC_PATH."portafolio/";?>" <?php if(isset($portafolio)) echo "class=\"activo\"";?> ><span>Portafolio</span></a></li>
                <li><a href="<?php echo PUBLIC_PATH."blog/";?>" <?php if(isset($blog)) echo "class=\"activo\"";?> ><span>Blog</span></a></li>
                <li><a href="<?php echo PUBLIC_PATH."contacto/";?>" <?php if(isset($contacto)) echo "class=\"activo\"";?> ><span>Contacto</span></a></li>
            </ul>
        </div>
        <div id="buscador">
            <?php echo Form::open('blog/buscar/', 'post', array('id'=>'form_nav', 'name'=>'form_nav')); ?>
                <label>
                    <span>
                        <?php echo Form::text('parametro', array('class'=>'keywords', 'maxlenght'=>'50'), 'Búsqueda...'); ?>
                    </span>
                    <?php echo Form::submitImage('pagina/buscador.gif', array('name'=>'boton')); ?>
                </label>
            <?php echo Form::close(); ?>
        </div>
        <div class="clr"></div>
    </div>
    <div class="clr"></div>
</div>