<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Agregar nueva publicación</h1></div>
    <?php echo ExtForm::open('dc-admin/post/agregar/', 'post', array('class'=>'post'), true); ?>
    <div class="left large">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Publicación</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="post_titulo" class="desc">Título<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('post.titulo', array('class'=>'full'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="post_contenido" class="desc">Contenido<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::textarea('post.contenido', array('class'=>'tinymce large'), null, '', 0, false, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="post_etiqueta" class="desc">Etiquetas</label>
                        <div>
                            <?php echo ExtForm::text('etiquetas', array('class'=>'full'), null, '', false, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="post_usuario_id" class="desc">Autor<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::dbSelect('post.usuario_id', 'login', $usuarios, null, array('class'=>'font-normal lista medium', $amend => ''), Auth::get('id'), '', false, true); ?>
                            <?php if ($amend == ''): ?><div class="input-info">Es posible asignar esta publicación a otro autor.</div> <?php endif; ?>
                        </div>
                        <div>
                            <?php echo ExtForm::hidden('post.estado','', '');?>
                        </div>
                        <div>
                            <?php echo SecurityKey::generateKey(); ?>
                        </div>
                    </li>
                </ul>
                <?php View::partial('tiny_mce/post'); ?>
            </div>
        </div>
        <div class="break"></div>
    </div>

    <div class="right small">
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Publicar</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <div>
                            <label for="post_visibilidad" class="desc">Visibilidad</label>
                            <?php echo ExtForm::select('post.visibilidad', $visibilidad, array('class'=>'font-normal lista full'), null, '', false, true); ?>
                        </div>
                    </li>
                    <li class="twoColumns">
                        <label for="post_habilitar_comentarios" class="desc">Habilitar comentarios</label>
                        <div>
                            <span>
                                <?php echo ExtForm::radio('post.habilitar_comentarios', '1', array('class'=>''), $check_si, 'Si'); ?>
                            </span>
                            <span>
                                <?php echo ExtForm::radio('post.habilitar_comentarios', '2', array('class'=>''), $check_no, 'No'); ?>
                            </span>
                        </div>
                    </li>
                    <li>
                        <div>
                            <label for="post_fecha_publicacion" class="desc">Fecha de publicación</label>
                            <?php echo ExtForm::date('post.fecha_publicacion', array('class'=>'font-normal fecha medium'), date("Y-m-d"), '', true, true); ?>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <script type="text/javascript">
                        $(function() {$('#btn_borrador').click(function(){$("input[name=post[estado]]").attr('value','<?php echo Post::BORRADOR; ?>');});});
                    </script>
                    <div class="left small">
                        <span style="padding-right: 10px;"><?php echo ExtForm::submit('Borrador',array('id'=>'btn_borrador','name'=>'btn_borrador')); ?></span>
                    </div>
                    <script type="text/javascript">
                        <?php if(Session::get('grupo_id') == Grupo::COLABORADOR) { ?>
                        $(function() {$('#btn_publicar').click(function(){$("input[name=post[estado]]").attr('value','<?php echo Post::PENDIENTE; ?>');});});
                        <?php } else { ?>
                        $(function() {$('#btn_publicar').click(function(){$("input[name=post[estado]]").attr('value','<?php echo Post::PUBLICADO; ?>');});});
                        <?php } ?>
                     </script>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Publicar',array('id'=>'btn_publicar','name'=>'btn_publicar')); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
        <div class="break"></div>
        <div class="box ui-corner-all ui-widget-content" id="categoria-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Categorías</h3></div>
            <div class="box-contenido box-taxonomia box-form font-small">
                <ul>
                    <li>
                        <?php
                        foreach($categorias as $fila):
                            if(isset($categoria)) {
                                foreach($categoria as $item):
                                    if($fila->id == $item) {
                                        $checked = true;
                                        break;
                                    } else {
                                        $checked = false;
                                    }
                                endforeach;
                            } else {
                                $checked = ($fila->id == CATEGORIA_POR_DEFECTO) ? true : false;
                            }
                        ?>
                        <div>
                            <?php echo ExtForm::check('categorias[]', $fila->id, '', $checked, $fila->nombre); ?>
                        </div>
                        <?php endforeach; ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="clr"></div>
    </div>
    <?php echo ExtForm::close(); ?>
    <div class="clr"></div>
</div>

<!-- Alertas -->
<script type="text/javascript">
    var link_action;
    $('a','.row-action-delete').click(function(event){ event.preventDefault(); link_action = $(this).attr('href'); $('#eliminar-post').dialog('open'); });
    $(function() { $("#eliminar-post").dialog({ autoOpen: false, width: 400, height:155, modal: true, buttons: { 'Cancelar': function() { $(this).dialog('close'); } ,'Aceptar': function() { location.href = link_action; } } }); });
</script>
<div id="eliminar-post" title="<?php echo APP_NAME; ?>" class="confirm-dialog">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseas borrar permantentemente esta publicación?. </p>
</div>
<script type="text/javascript">
    $(function() { $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('ui-state-highlight tr-hover'); },function() {});});
 </script>
