<?php View::partial('mensaje'); ?>

<div class="contenido">
    <div class="left large"><h1 class="text-shadow">Publicaciones <span><?php if(isset($parametro)) { echo "Resultado de la búsqueda para \"$parametro\""; }; ?></span></h1></div>
    <div class="right small"><?php View::partial('admin/form_busqueda', false, array('action'=>'post')); ?></div>
    <div class="clr"></div>

    <?php View::partial('admin/post/sub-nav'); ?>

    <div class="full">

        <div class="box ui-corner-all ui-widget-content" id="data-grid">
            <table class="data-grid" cellspacing="0">
                <thead class="ui-state-default ui-corner-tl ui-corner-tr">
                    <tr class="text-shadow">
                        <th class="columna-check">&nbsp</th>
                        <th class="columna-titulo">Título</th>
                        <th class="columna-autor">Autor</th>
                        <th class="columna-categoria">Categorías</th>
                        <th class="columna-etiqueta">Etiquetas</th>
                        <th class="columna-comentario img"><?php echo Html::img('admin/comentario.png', 'Comentarios', array('class'=>'data-grid')); ?></th>
                        <th class="columna-fecha">Fecha</th>
                    </tr>
                </thead>
                <tbody>
                    <?php ExtDate::loadDate(); ?>
                    <?php while($fila = $post->fetchPagedRow())  { ?>
                    <?php $taxonomias = $fila->getTaxonomiaPost(); ?>
                    <?php $tax_categorias = array(); ?>
                    <?php $tax_etiquetas = array(); ?>
                    <?php foreach($taxonomias as $taxonomia): ?>
                        <?php if($taxonomia->tipo == Taxonomia::CATEGORIA) { ?>
                            <?php $tax_categorias[] = Html::link('dc-admin/post/listar/'.$actual.'/categoria/'.$taxonomia->url.'/', $taxonomia->nombre);?>
                        <?php } else { ?>
                            <?php $tax_etiquetas[] = Html::link('dc-admin/post/listar/'.$actual.'/etiqueta/'.$taxonomia->url.'/', $taxonomia->nombre);?>
                        <?php } ?>
                    <?php endforeach; ?>
                    <?php $validKey = md5($fila->id.$ipKey.$expKey.'post'); ?>
                    <tr>
                        <th>&nbsp;</th>
                        <td class="">
                            <span class="strong post-titulo font-large"><?php echo Html::link($fila->getUrlPost('blog'), $fila->titulo, array('target'=>'_blank')); ?></span> <span class="strong font-medium post-estado"><?php if($fila->estado == Post::PENDIENTE) { echo ' - Pendiente'; } if($fila->estado == Post::BORRADOR) { echo ' - Borrador'; } if($fila->visibilidad == Post::PRIVADO) { echo ' - Privada'; } ?></span>
                            <div class="row-info font-small"><?php echo Truncar::palabra($fila->resumen, 17); ?></div>
                            <div class="row-actions font-small">
                                <span class="row-action-show"><?php echo Html::link($fila->getUrlPost('blog'),'Ver',array('target'=>'_blank'));?> | </span>
                                <span class="row-action-edit"><?php echo Html::link("dc-admin/post/editar/$fila->id/key/$validKey/",'Editar');?> | </span>
                                <span class="row-action-delete"><?php echo Html::link("dc-admin/post/eliminar/$fila->id/key/$validKey/",'Eliminar');?></span>
                            </div>
                        </td>
                        <td class="font-small"><?php echo Html::link('dc-admin/post/listar/'.$actual.'/usuario/'.$fila->login.'/', $fila->login);?></td>
                        <td class="font-small font-left"><?php echo join(', ', $tax_categorias); ?></td>
                        <td class="font-small"><?php echo join(', ', $tax_etiquetas); ?></td>
                        <td class="font-small font-center strong"><?php echo Html::link('dc-admin/comentarios/listar/post/'.$fila->slug.'/', $fila->comentarios);?></td>
                        <td class="font-small"><?php echo ExtDate::getHowLong($fila->fecha_publicacion);?> <br /><?php  if($fila->estado == Post::PUBLICADO) { echo 'Publicada'; } else { echo 'Última <br /> modificación'; }; ?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php View::partial('paginacion',false,array('objeto'=>$post, 'tipo'=>'dc-admin')); ?>
        </div>
        <div class="break"></div>
        
    </div>
    
</div>

<!-- Alertas -->
<script type="text/javascript">
    var link_action;
    $('a','.row-action-delete').click(function(event){ event.preventDefault(); link_action = $(this).attr('href'); $('#eliminar-post').dialog('open'); });
    $(function() { $("#eliminar-post").dialog({ autoOpen: false, width: 400, height:155, modal: true, buttons: { 'Cancelar': function() { $(this).dialog('close'); } ,'Aceptar': function() { location.href = link_action; } } }); });
</script>
<div id="eliminar-post" title="Dailyscript - Web | App | Media" class="confirm-dialog">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseas borrar permantentemente esta publicación?. </p>
</div>
<script type="text/javascript">
    $(function() {        
        $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('tr-hover'); },function() {});
    });
 </script>
