<?php View::partial('mensaje');?>
<style>
p{
    border: 1px solid #999;
    display: inline-block;
    margin: 3px;
    min-height: 85px;
    vertical-align: top;
    width: 200px;
}
p img {
    float: left;
    margin: 5px;
}
p a {
    color: blue !important;
}
</style>
<?php print APP_PATH; ?>
<div class="contenido">
    <div class="full"><h1 class="text-shadow">Biblioteca de Multimedios</h1></div>
    <?php echo ExtForm::openMultipart(null, 'post', array('class'=>'post'), true); ?>
    <div class="left medium" id="tabs">
        <ul>
            <li><a href="#tabs-1">Subir Imagen</a></li>
            <li><a href="#tabs-2">Biblioteca</a></li>
        </ul>
        <div class="left full" id="tabs-1">
                    <label for="usuario_nombre" class="desc">Seleccione una imagen</label>
                    <div>
                        <?php echo extForm::file('archivo'); ?>
                    </div>
                    <div style="width:100%;">
                        <div>
                            <?php echo SecurityKey::generateKey(); ?>
                        </div>
                        <div class="right small">
                            <span><?php echo ExtForm::submit('Subir Imagen',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                        </div>
                        <div class="clr"></div>
                    </div>
        </div>
        <?php echo ExtForm::close(); ?>
        <div class="left full" id="tabs-2">
            <?php
                // $i=1;
                $finfo = finfo_open(FILEINFO_MIME_TYPE); // devuelve el tipo mime de su extensión
                $ruta = PUBLIC_PATH.$path;
                foreach ($archivos as $archivo) {
                    $tipo = finfo_file($finfo, $system_path.$archivo);
                    $icono = Utils::fileInfo($ruta,$archivo,$tipo);
                    echo "<p>".$icono['icono'].$archivo."<br><a href='#' onClick='importar(\"".$archivo."\",\"".$icono['tipo']."\");'>Insertar</a></p>\n";
                    // if($i == 3 ) {echo "<br/>";$i=1;}
                    // $i++;
                }
                finfo_close($finfo);
            ?>
        </div>
    </div>
</div>
 <script>
$(function() {
$( "#tabs" ).tabs();
});
function importar(archivo,tipo) {
    if (tipo == 'image') {
        objeto="<img src='<?php echo $ruta ?>"+archivo+"'/>";
    } else {
        objeto="<a href='<?php echo $ruta ?>"+archivo+"'/>"+archivo+"</a>";
    }
    window.opener.e(objeto);
    // window.close();
}
</script>