<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Agregar nueva usuario</h1></div>
    <?php echo ExtForm::open('dc-admin/usuario/agregar/', 'post', array('class'=>'post'), true); ?>
    <div class="left medium">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Datos Personales</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Nombre<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('usuario.nombre', array('class'=>'large'), $nombre, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_apellido" class="desc">Apellido<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('usuario.apellido', array('class'=>'large'), $apellido, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_email" class="desc">email<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('usuario.mail', array('class'=>'medium email'), $email, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_login" class="desc">Login<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('usuario.login', array('class'=>'medium usuario', 'readonly' => 'readonly'), $login, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_password" class="desc">Contrase&ntilde;a<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::pass('usuario.password', array('class'=>'small pass'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="repasswd" class="desc">Confirma contrase&ntilde;a<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::pass('repasswd', array('class'=>'small'), null, '', true, true); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="break"></div>
    </div>

    <div class="right medium">
        <!-- Perfil -->
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Perfil</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <div>
                            <label for="usuario_grupo_id" class="desc">Tipo de usuario</label>
                            <?php
                            $data = array('grupo', 'getGruposPermitidos');
                            echo ExtForm::dbSelect('usuario.grupo_id', 'grupo_descripcion', $data, '-- Seleccione -- ', array('class'=>'font-normal lista full'), null, '', false, true); ?>
                        </div>
                    </li>
                    <li>
                        <div>
                            <label for="usuario_registrado_at" class="desc">Fecha de creación</label>
                            <?php echo ExtForm::text('usuario.registrado_at', array('class'=>'font-normal fecha small', 'disabled' => 'disabled'), date("Y-m-d"), '', true, true); ?>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <script type="text/javascript">
                        $(function() {$('#btn_publicar').click(function(){$("input[name=post[estado]]").attr('value','<?php echo Post::PUBLICADO; ?>');});});
                     </script>
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Actualizar Perfil',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>

        <div class="break"></div>

        <!-- Redes Sociales -->
        <div class="box ui-corner-all ui-widget-content">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Redes Sociales</h3></div>
            <div class="box-contenido box-form">
                <?php View::partial('twitter/cuenta'); ?>
            </div>
        </div>

        <div class="break"></div>
    </div>

<?php echo Tag::js('sha1')."\n"; ?>
<!-- Alertas -->
<script type="text/javascript">
    $(function() { $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('ui-state-highlight tr-hover'); },function() {});});

    function mensaje(div, mensaje, tipo){
        $('#' + div).html(mensaje);
        if (tipo == 'info') {
            $('#' + div).removeClass('err');
            $('#' + div).addClass('succ');
            $("input[type='submit']").removeAttr('disabled', 'disabled');
            $("input[type='submit']").removeClass('ui-button-disabled ui-state-disabled');
        } else if (tipo == 'warn') {
            //$('#' + div).css('color', 'orange'); pendiente
        } else {
            $('#' + div).removeClass('succ');
            $('#' + div).addClass('err');
            $("input[type='submit']").addClass('ui-button-disabled ui-state-disabled');
            $("input[type='submit']").attr('disabled', 'disabled');
        }
    }

    $('#usuario_mail').keyup(function(){
        mail = $(this).val();

        if ( mail.length > 10 && mail.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$') ) {
            $.post(
                '../checkEmail',
                {
                    email: mail
                },
                function(data){
                    if (data.status == 'OK') {
                        mensaje('err_usuario_mail', 'Disponible', 'info');
                    } else {
                        mensaje('err_usuario_mail', 'Este email ya esta asignado a un usuario');
                    }
                },
                'json'
            );
        } else {
            mensaje('err_usuario_mail', '');
        }
    });//    ^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$

    $('#repasswd').keyup(function(){
        pass = $('#usuario_password').val();
        repass = $(this).val();

        if ( pass == repass ) {
            mensaje('err_repasswd', '', 'info');
        } else {
            mensaje('err_repasswd', 'Las contrase&ntilde;as no coinciden');
        }
    });

    $('form').submit(function(){
        var pass = $("input[type='password']").val();
        $("input[type='password']").val(hex_sha1(pass));
    });

 </script>
