<?php //echo Tag::js('tiny_mce/jquery.tinymce'); ?>
<?php echo Tag::js('tiny_mce/tiny_mce'); ?>

<script language="javascript" type="text/javascript">
   
    function cargarTinyMCE() {
	tinyMCE.init({
		mode : "textareas",
		elements: "quickpress",
		theme : "advanced",
		plugins: "fullscreen, advlink, advimage",
		theme_advanced_buttons1 : "bold, italic, underline, separator, justifyleft, justifycenter, justifyright, justifyfull ",
		theme_advanced_buttons2 : "bullist,numlist,separator,outdent,indent,separator,undo,redo",
		theme_advanced_buttons3 : "image, link, fullscreen",
		theme_advanced_toolbar_location: "top",
		theme_advanced_toolbar_align: "left"	});
    }
    /*
    $().ready(function() {
        tinyMCE.init({
            mode : "textareas",
            elements: "quickpress",
            theme : "advanced",
            plugins: "fullscreen, advlink, advimage",
            theme_advanced_buttons1 : "bold, italic, underline, separator, justifyleft, justifycenter, justifyright, justifyfull ",
            theme_advanced_buttons2 : "bullist,numlist,separator,outdent,indent,separator,undo,redo",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left"
        });
        
        $('textarea.tinymce').tinymce({
            language: 'es',
            mode:"textareas",
            elements: "quickpress",
            theme:"advanced",            
            theme_advanced_buttons1:"bold,italic,strikethrough,underline,|,bullist,numlist,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull",
            theme_advanced_buttons2:"formatselect,forecolor,|,removeformat,|,outdent,indent,|,undo,redo",
            theme_advanced_buttons3:"",
            theme_advanced_buttons4:"",            
            theme_advanced_toolbar_location:"top",
            theme_advanced_toolbar_align:"left",
            theme_advanced_statusbar_location:"bottom",
            theme_advanced_resizing:"1",
            theme_advanced_resize_horizontal:""           
        });
    });*/
</script>