<!-- Load jQuery build -->
<?php echo Tag::js('tiny_mce/jquery.tinymce'); ?>
<?php echo Tag::js('tiny_mce/tiny_mce'); ?>
<script language="javascript" type="text/javascript">
    $().ready(function() {
        $('textarea.tinymce').tinymce({
            language: 'es',mode:"textareas",elements: "quickpress",
            plugins: "autolink,lists,spellchecker,safari,media,tabfocus,iespell",
            theme:"advanced",theme_advanced_buttons1:"bold,italic,strikethrough,underline,separator,bullist,numlist,blockquote,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,undo,redo,separator,link,unlink,image,media",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_buttons4:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_resizing : false,theme_advanced_statusbar_location : "none", content_css : "/dcm/css/post.css"
        });
    });
</script>