<?php echo Tag::js('tiny_mce/jquery.tinymce'); ?>
<?php echo Tag::js('tiny_mce/tiny_mce'); ?>
<script language="javascript" type="text/javascript">
    $().ready(function() {
        $('textarea.tinymce').tinymce({
            language: 'es',mode:"textareas",elements: "quickpress",
            plugins: "safari,tabfocus",
            theme:"advanced",theme_advanced_buttons1:"bold,italic,strikethrough,underline,separator,bullist,numlist,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,undo,redo",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_buttons4:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left"            
        });
    });
</script>