<div class="contenido">
    <a id="descripcion"></a>
    <!-- Mensaje -->
    <div class="contenedor-mensaje">
        <div class="mensaje">                        
            <?php View::content(); echo "\r\n"; ?>
        </div>
    </div>
    <h2 class="contenido-titulo">La empresa</h2>
    <div class="left">
        <p>Dailyscript es una empresa joven, innovadora y creativa, capaz de entender y escuchar a nuestros
        clientes, brindando soluciones hechas a su medida que permitan la automatización de sus procesos,
        con el fin de obtener ventajas competitivas mediante el uso de las tecnologías de la información 
        y la comunicación.</p>
        <a id="mision"></a>
        <h3 class="contenido-subtitulo">Misión</h3>
        <div class="texto">
            <p>Nuestra misión fundamental es la creación de soluciones orientadas a la web que logren
            la automatización de procesos y que brinden un apoyo a la toma de decisiones de administradores
            y directivos en una organización, a través del uso de las tecnologías de la información y la comunicación,
            satisfaciendo las necesidades de nuestros clientes y cumpliendo con sus expectativas de servicio.</p>
        </div>
        <a id="vision"></a>
        <h3 class="contenido-subtitulo">Visión</h3>
        <div class="texto">
            <p>Nuestra misión fundamental es la creación de soluciones orientadas a la web que logren
            la automatización de procesos y que brinden un apoyo a la toma de decisiones de administradores
            y directivos en una organización, a través del uso de las tecnologías de la información y la comunicación,
            satisfaciendo las necesidades de nuestros clientes y cumpliendo con sus expectativas de servicio.</p>
        </div>
        <a id="valores"></a>
        <h3 class="contenido-subtitulo">Nuestra filosofía</h3>
        <div class="texto">
            <p>Nuestra misión fundamental es la creación de soluciones orientadas a la web que logren
            la automatización de procesos y que brinden un apoyo a la toma de decisiones de administradores
            y directivos en una organización, a través del uso de las tecnologías de la información y la comunicación,
            satisfaciendo las necesidades de nuestros clientes y cumpliendo con sus expectativas de servicio.</p>
        </div>
    </div>
    <div class="right">
        <h3 style="text-align: center;" class="contenido-subtitulo">Know - how</h3>
        <div class="texto">
            <h3 class="contenido-subtitulo">Planeación</h3>
            <?php echo Html::img('pagina/kh_planeacion.png', 'planeacion', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Es la primera etapa de cada proyecto. </strong><br />
            Escuchamos a nuestros clientes de manera especial; determinamos los alcances, 
            objetivos, arquitectura e infraestrucura técnica.
            <?php echo Html::link('know-how/#planeacion','Mas »');?><br />
            </p>

            <h3 class="contenido-subtitulo">Producción</h3>
            <?php echo Html::img('pagina/kh_produccion.gif', 'producción', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Aquí marcamos la diferencia. </strong><br />
            Este es el proceso en donde  más interactuamos con el cliente mostrando los
            avances y prototipos de cada proyecto.  Nuestro equipo se encarga del análisis de las pruebas
            y se utiliza como verificación del correcto funcionamiento del mismo.
            <?php echo Html::link('know-how/#produccion','Mas »');?><br />
            </p>
            
            <h3 class="contenido-subtitulo">Feedback</h3>
            <?php echo Html::img('pagina/kh_analisis.png', 'feedback', array('border'=>'0', 'width'=>'82', 'heigth'=>'82', 'class'=>'floated')); ?>
            <p><strong>Porque no es solamente producir.</strong><br />
            Una vez nuestro trabajo es entregado analizamos los indicadores de usabilidad, 
            estabilidad, crecimiento y tráfico* para mejorar cada vez mas calidad de nuestros productos.
            <?php echo Html::link('know-how/#feedbak','Mas »');?><br /></p>
        </div>
        <div class="bg"></div>
    </div>    
    <div class="clr"></div>
</div>
  