<?php
// Si poseemos una identidad guardada el mostramos los datos sino vamos al 
// link para dar permisos para que nuestra aplicacion puede publicar los Tweet
Load::model('twitter');
$modelo = new Twitter();
$modelo->cuenta();
$twitterdata = $modelo->getData(); 
?>
        <!-- Redes Sociales -->
        <div class="box ui-corner-all ui-widget-content">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Redes Sociales</h3></div>
            <div class="box-contenido box-form">
                <ul>
                <?php if ($twitterdata): ?>
                    <li>
                        <div>
                			<label class="desc">Tu cuenta en Twitter</label>
                			<img src="<?php echo $twitterdata['image']; ?>" style="float:left; margin-right: 5px;"><br/>
                			<a href="<?php echo $twitterdata['profile']; ?>" target="_blank">Ver Perfil</a><br/>
                			<a href="<?php echo PUBLIC_PATH; ?>dc-admin/usuario/eliminarTwitter/<?php echo $twitterdata['id']; ?>">Desasociar Cuenta</a><br/>
                			<!-- <a href="<?php echo PUBLIC_PATH; ?>redes/tweet/">Envia un Tweet</a> -->
                        </div>
                    </li>
                <?php else: ?>
                    <li>
                        <div>
                            <label for="link_twitter" class="desc">Asociar cuenta de Twitter</label>
                            <a href="<?php echo $modelo->getLink(); ?>" id="link_twitter">Login</a>
                        </div>
                    </li>
                <?php endif; ?>
                </ul>
            </div>
        </div>
        <div class="break"></div>
        <!-- Redes Sociales -->

