<?php Tag::css('jquery-ui/jquery.ui.all');?>
<?php Tag::css('formulario');?>
<?php echo Tag::js('jquery/jquery-ui.min');?>
<?php echo Tag::js('formulario');?>

<div class="contenido">
    
    <!-- Mensaje -->
    <?php View::partial('mensaje'); ?>
    
    <h2 class="titulo-error"><?php echo isset($detalle_error) ? $detalle_error : APP_NAME; ?></h2>
    <p>Ops!, no podemos encontrar lo que estás buscando. Quizás la búsqueda te ayudará!.</p>
    <div class="left">        
        <div class="form">
            <?php echo ExtForm::open('blog/buscar/', 'post', array('id'=>'formulario', 'name'=>'formulario'), true); ?>
            <ul>
                <li class="twoColumns">
                    <div>
                        <span>
                            <?php echo ExtForm::text('parametro', array('class'=>'full'), null, 'Búsqueda', true, true); ?>
                        </span>
                        <span>
                            <?php echo ExtForm::submitImage('pagina/enviar.png'); ?>
                        </span>                        
                    </div>
                </li>                
            </ul>            
            <?php echo Form::close(); ?>
            <div class="clr"></div>
        </div>
    </div>
    
    <div class="clr"></div>
    
</div>
<script type="text/javascript">
    $(function() { $("#error-form").dialog({ autoOpen: false, width: 400, height:165, modal: true, buttons: { 'Aceptar': function() { $(this).dialog('close'); } } }); });
</script>
<div id="error-form" title="<?php echo NOMBRE_DEL_BLOG ?>" class="confirm-dialog">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Se han encontrado errores al procesar el formulario. </p>
    <p>Por favor verifica los datos e intenta nuevamente</p>
</div>
  