<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Dailyscript &copy; <?php echo date("Y");?>"/>
    <meta name="robots" content="noindex,nofollow" />
    <title><?php echo $title ?></title>
    <?php Tag::css('admin') ?>
    <?php Tag::css('style') ?>
    <?php Tag::css('formulario'); ?>
    <?php Tag::css('jquery-ui/jquery.ui.all');?>
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('menu');?>
    <?php echo Tag::js('formulario'); ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>
    <?php echo Tag::js('jquery/jquery-ui.min');?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp');?>
    <script type="text/javascript">
        $(function() {$('input:submit, input:button, input:reset').button();$('a','#menu-principal').button();$('a','.box-botones').button();});
        // <![CDATA[
            var myMenu;window.onload = function() { myMenu = new Menu("menu-items"); myMenu.init(); };
	// ]]>
    </script>
    </head>
    <body>

        <!-- Cabecera -->
        <div id="cabecera">
            <div class="left medium">
                <p class="font-normal"><?php echo Html::link('blog/','Ver sitio', array('target'=>'_blank','class'=>'font-normal')); ?></p>
            </div>
            <div class="right medium">
                <p class="font-normal">Hola, <?php echo Html::link('dc-admin/perfil/', Session::get('usuario'), array('class'=>'font-normal') ); ?> | <?php echo Html::link('dc-admin/usuario/salir/', 'Cerrar sesión', array('class'=>'font-normal')); ?></p>
            </div>
            <div class="clr"></div>
        </div>

        <!-- Pagina -->
        <div id="cuerpo">

            <!-- Menu -->
            <div id="menu">
                <?php View::partial('admin/menu'); ?>
            </div>

            <!-- Contenedor -->
            <div id="envoltura">
                <div id="contenedor">
                    <?php View::content(); ?>
                </div>
            </div>

            <div class="clr"></div>

        </div>

        <!-- Pie -->
        <div id="pie">
            <div class="left medium"><p>© Copyright <a href="http://dailyscript.com.co">Dailyscript</a>. Todos los derechos reservados. <a href="http://dailyscript.com.co/contacto/">Contacto</a></p></div>
            <div class="right medium"><p>Versión 0.1a - Tiempo de respuesta: <?php echo round((microtime(1)-START_TIME),4),' seg.'?> </p></div>
            <div class="clr"></div>
        </div>

        <!-- Alertas -->
        <script type="text/javascript">
            $(function() { $("#error-form").dialog({ autoOpen: false, width: 400, height:165, modal: true, buttons: { 'Aceptar': function() { $(this).dialog('close'); } } }); });
        </script>
        <div id="error-form" title="<?php echo APP_NAME; ?>" class="confirm-dialog">
            <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Se han encontrado errores al procesar el formulario. </p>
            <p>Por favor verifica los datos e intenta nuevamente</p>
        </div>

    </body>
</html>
