<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Dailyscript &copy; 2010" />
    <meta name="robots" content="noindex,nofollow" />
    <title><?php echo $title ?></title>
    <?php Tag::css('admin') ?>
    <?php Tag::css('style') ?>
    <?php Tag::css('formulario'); ?>
    <?php Tag::css('jquery-ui/jquery.ui.all');?>
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('menu');?>
    <?php echo Tag::js('formulario'); ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>
    <?php echo Tag::js('jquery/jquery-ui.min');?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp');?>
    <script type="text/javascript">
        $(function() {$('input:submit, input:button, input:reset').button();$('a','#escritorio').button();$('a','.box-botones').button();});        
        // <![CDATA[
            var myMenu;window.onload = function() { myMenu = new Menu("menu"); myMenu.init(); };
	// ]]>
    </script>   
    </head>
    <body>

        <!-- Cabecera -->
        <div id="contenedor-cabecera">
            <div id="cabecera">
                <div id="cabecera-left">
                    <p><?php echo Html::link('blog/','Ver sitio', array('target'=>'_blank')); ?></p>
                </div>
                <div id="cabecera-right">
                    <p>Hola, <?php echo Html::link('dc-admin/perfil/', Session::get('usuario') ); ?> | <?php echo Html::link('dc-admin/usuario/salir/', 'Cerrar sesión'); ?></p>
                </div>
            </div>
            <div class="clr"></div>
        </div>     

        <!-- Cuerpo -->
        <div id="contenedor-pagina">
            
            <!-- Menu -->
            <div id="contenedor-menu">
                <div id="escritorio"><?php echo Html::link('dc-admin/','Principal',array('title'=>'Página de administración')); ?></div>
                <div id="menu" class="menu principal ui-widget-content ui-corner-all">
                    <div class="collapsed">
                        <span>Publicaciones</span>
                        <?php echo Html::link('dc-admin/post/','Listar'); ?>
                        <?php echo Html::link('dc-admin/post/agregar/','Añadir'); ?>
                        <?php echo Html::link('dc-admin/categoria/','Categorias'); ?>
                        <?php echo Html::link('dc-admin/etiqueta/','Etiquetas'); ?>
                    </div>
                    <div class="collapsed">
                        <span>Comentarios</span>
                        <?php echo Html::link('dc-admin/comentario/','Comentarios'); ?>
                    </div>
                    <div class="collapsed">
                        <span>Enlaces</span>
                        <?php echo Html::link('dc-admin/enlace/','Enlaces'); ?>
                        <?php echo Html::link('dc-admin/enlace/agregar/','Agregar nuevo'); ?>
                    </div>
                    <div class="collapsed">
                        <span>Usuarios</span>
                        <?php echo Html::link('dc-admin/usuario/','Usuarios'); ?>
                        <?php echo Html::link('dc-admin/usuario/agregar/','Agregar'); ?>
                    </div>
                    <div class="collapsed">
                        <span>Ajustes</span>
                        <?php echo Html::link('dc-admin/ajuste/comentarios/','Comentarios'); ?>
                    </div>
                </div>                                                                
            </div>
            
            <!-- Contenedor principal -->
            <div id="contenedor-cuerpo">
                <!-- Contenido -->
                <div id="contenedor-contenido">
                    <?php View::content(); ?>
                </div>
                <div class="clr"></div>
            </div>                       
            <div class="clr"></div>
        </div>        

        <!-- Pie -->
        <div id="contenedor-pie">
            <div id="pie">
                <p class="left">© Copyright <a href="http://dailyscript.com.co">Dailyscript</a>. Todos los derechos reservados. <a href="http://dailyscript.com.co/contacto/">Contacto</a></p>
                <p class="right">Versión 0.1a</p>
                <div class="clr"></div>
            </div>
            <div class="clr"></div>
        </div>

        <!-- Alertas -->
        <script type="text/javascript">
            $(function() { $("#error-form").dialog({ autoOpen: false, width: 400, height:165, modal: true, buttons: { 'Aceptar': function() { $(this).dialog('close'); } } }); });
        </script>
        <div id="error-form" title="Dailyscript - Web | App | Media" class="confirm-dialog">
            <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Se han encontrado errores al procesar el formulario. </p>
            <p>Por favor verifica los datos e intenta nuevamente</p>
        </div>
        
    </body>
</html>
