<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Dailyscript &copy; 2010" />    
    <meta name="robots" content="noindex,nofollow" />    
    <title><?php echo $title ?></title>
    <?php Tag::css('default') ?>
    <?php Tag::css('style') ?>    
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>    
    <script type="text/javascript">
        $(document).ready(function(){            
            $("#logo,#navegador").hide().fadeIn(1500);
        });        
    </script>   
    </head>
    <body>

        <!-- Cabecera -->
        <?php View::partial('dailyscript/cabecera');?>

        <!-- Navegador -->
        <?php View::partial('dailyscript/navegador', false, array($controller_name=>$controller_name) );?>

        <!-- Cuerpo -->
        <div id="pagina">
            <!-- Contenedor principal -->
            <div class="contenedor">
                <!-- Contenido -->
                <?php View::content(); ?>
              <div class="clr"></div>
            </div>
        </div>

        <!-- Extra -->
        <?php View::partial('dailyscript/extra');?>

        <!-- Pie -->
        <?php View::partial('dailyscript/pie');?>
        
    </body>
</html>
