<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="copyright" content="Dailyscript &copy; 2010" />
    <meta name='robots' content='noindex,nofollow' />
    <title><?php echo $title ?></title>
    <?php Tag::css('login') ?>
    <?php Tag::css('formulario') ?>
    <?php Tag::css('style') ?>
    <?php Tag::css('jquery-ui/jquery.ui.all');?>
    <?php echo Html::includeCss() ?>
    <?php echo Tag::js('jquery/jquery.min'); ?>
    <?php echo Tag::js('jquery/jquery-ui.min');?>
    <?php echo Tag::js('formulario'); ?>
    <?php echo Tag::js('validar'); ?>
    <?php echo Tag::js('sha1')."\n"; ?>
    <style type="text/css">
        .ui-dialog { padding: .3em; }
        .validateTips { border: 1px solid transparent; padding: 0.3em; text-align: center; font-size: 1em; color: red;}
        .login-error { border: 1px solid red;}
    </style>
    </head>

    <body>
        <div id="contenedor-cabecera">
            <div id="cabecera">
                <p><?php echo Html::link('', '« Volver a la página principal'); ?></p>
            </div>
        </div>
        <div id="pagina">
            <div class="contenedor">
                <?php View::content(); ?>
              <div class="clr"></div>
            </div>
        </div>
        <script type="text/javascript">
            $(function() { $("#error-form").dialog({ autoOpen: false, width: 400, height:165, modal: true, buttons: { 'Aceptar': function() { $(this).dialog('close'); } } }); });
        </script>
        <div id="error-form" title="Dailyscript - Web | App | Media" class="confirm-dialog">
            <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Se han encontrado errores al procesar el formulario. </p>
            <p>Por favor verifica los datos e intenta nuevamente</p>
        </div>       
    </body>
</html>
<script type="text/javascript">
$(function() {
    tips = $(".validateTips");
    function updateTips(t) {tips.text(t).addClass('ui-state-highlight');setTimeout(function() {tips.removeClass('ui-state-highlight', 1500);}, 500);}
    function checkLength(o,n,min,max,text) { if ( (o.val().length > max) || (o.val().length < min) ) { o.addClass('login-error'); updateTips(text + " debe tener de "+min+" a "+max+" caracteres.");o.focus(); return false;} else {return true;}}
    function checkRegexp(o,regexp,n) {if ( !( regexp.test( o.val() ) ) ) {o.addClass('login-error');updateTips(n);o.focus();return false;} else {return true;}}

    $("#mensaje").click(function() {
        setTimeout(function(){ $("#mensaje").hide('clip',600); }, 400);
        return false;
    });

    $("input:submit",'#contenido-formulario').click(function() {
        var login       = $("#login");
        var pass        = $("#pass");
        var bValid = true;
        bValid = bValid && checkLength(login,"Usuario",4,10,"El usuario");
        if (bValid) { login.removeClass('login-error'); }
        bValid = bValid && checkLength(pass,"Contraseña",6,20, "La contraseña");
        if (bValid) { pass.removeClass('login-error'); }
        bValid = bValid && checkRegexp(login,/^([A-ZÑ0-9])+$/i,"El usuario debe tener caracteres alfanuméricos.");
        if (bValid) { login.removeClass('login-error'); }
        bValid = bValid && checkRegexp(pass,/^([A-ZÑ0-9\.\-\_])+$/i,"La clave debe tener caracteres [A-Z]-[0-9]-[.-]");
        if (bValid) { pass.removeClass('login-error'); }
        if (bValid) { login.removeClass('login-error');pass.removeClass('login-error');document.formulario.pass.value = hex_sha1(document.formulario.pass.value);return true;}
        else { return false}
    });
});
</script>