<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Ajuste Generales</h1></div>
    <?php echo ExtForm::open(null, 'post', array('class'=>'post'), true); ?>
    <div class="left medium">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Empresa</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Nombre del Blog<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('blog.nombre_blog', array('class'=>'medium'), $config['nombre_blog'], '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_nombre" class="desc">Post por Página<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('blog.post_por_pagina', array('class'=>'small'), $config['post_por_pagina'], '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_apellido" class="desc">Post por Widget<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('blog.post_por_widget', array('class'=>'medium'), $config['post_por_widget'], '', true, true); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <div class="right medium">
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Descripción de la Empresa</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Categoria por Defecto</label>
                        <div>
                            <?php echo ExtForm::text('blog.categoria_por_defecto', array('class'=>'medium'), $config['categoria_por_defecto'], '', false, true); ?>
                        </div>
                    </li>
                    <li class="twoColumns">
                        <label for="general.favicon" class="desc">Habilitar Comentarios</label>
                        <div>
                            <span>
                                <?php echo ExtForm::radio('blog.habilitar_comentarios', 'on', array('class'=>''), $comentarioOn, 'Si'); ?>
                            </span>
                            <span>
                                <?php echo ExtForm::radio('blog.habilitar_comentarios', 'off', array('class'=>''), $comentarioOff, 'No'); ?>
                            </span>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Guardar Configuración',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                    </div>
                    <?php View::partial('tiny_mce/post'); ?>
                    <div class="clr"></div>
                </div>
            </div>
        </div>

    </div>