<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Ajuste Generales</h1></div>
    <?php echo ExtForm::open('dc-admin/usuario/agregar/', 'post', array('class'=>'post'), true); ?>
    <div class="left medium">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Empresa</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Razón Social<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('general.nombre', array('class'=>'medium'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_nombre" class="desc">RIF<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('general.rif', array('class'=>'small'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_apellido" class="desc">Titulo de Sitio<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('general.titulo', array('class'=>'medium'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_email" class="desc">Descripción Corta</label>
                        <div>
                            <?php echo ExtForm::text('general.descripcion', array('class'=>'large'), null, ''); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_login" class="desc">Correo Electrónico Administrativo<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('general.email', array('class'=>'medium email'), null, '', true, true); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="break"></div>

        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Descripción de la Empresa</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <div>
                            <?php echo ExtForm::textarea('general.direccion', array('class'=>'tinymce large'), null, '', 0, false, true); ?>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Guardar Configuración',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                    </div>
                    <?php View::partial('tiny_mce/post'); ?>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="right medium">
        <?php if ( Router::get('action') != 'editar' ) View::partial('redes_sociales/cuentas'); ?>
        <div class="break"></div>
    </div>