<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Ajustes</h1></div>
    <?php echo ExtForm::open('dc-admin/ajustes/publicaciones/', 'post', array('class'=>'post'), true); ?>
    <div class="full">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Publicaciones</h3></div>
            <div class="box-contenido box-form">
<!--                <ul>
                    <li>
                        <label for="post_titulo" class="desc">Título<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('post.titulo', array('class'=>'full'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="post_contenido" class="desc">Contenido<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::textarea('post.contenido', array('class'=>'tinymce large'), null, '', 0, false, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="post_etiqueta" class="desc">Etiquetas</label>
                        <div>
                            <?php echo ExtForm::text('etiquetas', array('class'=>'full'), null, '', false, true); ?>
                        </div>
                        <div>
                            <?php echo ExtForm::hidden('post.estado','', '');?>
                        </div>
                        <div>
                            <?php echo SecurityKey::generateKey(); ?>
                        </div>
                    </li>
                </ul>
                <div class="box-botones">
                    <div class="left small">
                        <span><?php echo ExtForm::submit('Publicar',array('id'=>'btn_publicar','name'=>'btn_publicar')); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>  -->
            </div>
        </div>
        <div class="break"></div>
    </div>

<!--    <div class="right small">
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Publicar</h3></div>
            <div class="box-contenido box-form">                    
                 Botones 
                
            </div>
        </div>                
        <div class="clr"></div>
    </div>-->
    <?php echo ExtForm::close(); ?>
    <div class="clr"></div>
</div>
