<?php Tag::css('jquery-ui/jquery.ui.all');?>
<?php Tag::css('formulario');?>
<?php echo Tag::js('jquery/jquery-ui.min');?>
<?php echo Tag::js('formulario');?>
<div class="contenido">
    <!-- Mensaje -->
    <div class="contenedor-mensaje">
        <div class="mensaje">                        
            <?php View::content(); echo "\r\n"; ?>
        </div>
    </div>
    <h2 class="contenido-titulo">Contáctenos</h2>
    <p>Estamos para resolver su inquietud; si desa puede ponerse en contacto con nosotros a través de cualquiera de estos medios!.</p>
    <div class="left">
        <h3 class="contenido-subtitulo">Formulario de contacto</h3>
        <div class="form">
            <?php echo ExtForm::open('contacto/', 'post', array('id'=>'formulario', 'name'=>'formulario'), true); ?>
            <ul>
                <li>
                    <div>                        
                        <?php echo ExtForm::text('contacto.nombre', array('class'=>'alfabetico full'), null, 'Nombre', true, true); ?>
                    </div>
                </li>                
                <li>
                    <div>                        
                        <?php echo ExtForm::text('contacto.empresa', array('class'=>'especial full'), null, 'Empresa', false, true); ?>
                    </div>
                </li>
                <li>
                    <div>                        
                        <?php echo ExtForm::text('contacto.email', array('class'=>'email full'), null, 'Email', true, true); ?>
                    </div>
                </li>                
                <li>
                    <div>                        
                        <?php echo ExtForm::text('contacto.asunto', array('class'=>'texto full', 'maxlength'=>'100'), null, 'Asunto', true, true); ?>
                    </div>
                </li>
                <li>
                    <div>                        
                        <?php echo ExtForm::textarea('contacto.mensaje', array('class'=>'texto large', 'maxlength'=>'1500'), null, 'Mensaje', 1500, true, true); ?>
                    </div>
                </li>                
            </ul>
            <div class="botones">
                <?php echo ExtForm::submitImage('pagina/enviar.png'); ?>
            </div>
            <?php echo Form::close(); ?>           
            <div class="clr"></div>
        </div>
    </div>
    <div class="right">
        <div class="texto">
            <h3 class="contenido-subtitulo">Encuéntrenos!</h3>
            <p>
               <strong>Dirección</strong>: <?php echo $empresa->direccion.", ".$empresa->ciudad." - ".$empresa->pais.".";?><br />
               <strong>Teléfono</strong>: <?php echo $empresa->telefono." ".$empresa->telefonoaux; ?><br />
               <strong>FAX:</strong> <?php echo $empresa->fax; ?><br />
               <strong>Móvil</strong>: <?php echo $empresa->movil." ".$empresa->movilaux; ?><br />
               <strong>E-mail</strong>: <span style="text-transform: lowercase;"><?php echo $empresa->email; ?></span><br />
               <strong>Horario</strong>: <?php echo $empresa->horario_atencion; ?>
            </p>
        </div>
        <div class="bg"></div>
    </div>
    <script type="text/javascript">
        $(function() { $("#error-form").dialog({ autoOpen: false, width: 400, height:165, modal: true, buttons: { 'Aceptar': function() { $(this).dialog('close'); } } }); });
    </script>
    <div id="error-form" title="Dailyscript - Web | App | Media" class="confirm-dialog">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Se han encontrado errores al procesar el formulario. </p>
        <p>Por favor verifica los datos e intenta nuevamente</p>
    </div>
    <div class="clr"></div>
</div>
  