<div class="form-busqueda">
    <?php $action = (isset($action) && ($action != '')) ? 'dc-admin/'.trim($action,'/').'/' : ''?>
    <?php echo ExtForm::open($action,'post',array('class'=>'form-busqueda'),true); ?>
    <ul>
        <li class="notStacked form-sup">
            <div style="float:right">
                <span class="font-normal">
                    <?php echo ExtForm::text('parametro', array('class'=>'texto full'), null, '',true,true); ?>
                </span>
                <span class="form-button">
                    <?php echo ExtForm::submit('Buscar'); ?>
                </span>
            </div>
        </li>
    </ul>
    <?php echo ExtForm::close(); ?>
</div>