<?php
Load::model('grupo');
?>
<div id="menu-principal"><?php echo Html::link('dc-admin/','Principal',array('title'=>'Página de administración','class'=>'text-shadow')); ?></div>
<div id="menu-items" class="menu principal ui-widget-content ui-corner-all">

    <?php if ( Session::get('nivel') < Grupo::COLABORADOR ): ?>
    <div class="collapsed">
        <span class="text-shadow">Publicaciones</span>
        <?php echo Html::link('dc-admin/post/listar/','Listar'); ?>
        <?php echo Html::link('dc-admin/post/agregar/','Añadir'); ?>
        <?php echo Html::link('dc-admin/categoria/','Categorias'); ?>
        <?php echo Html::link('dc-admin/etiqueta/','Etiquetas'); ?>
    </div>
    <?php endif; ?>

    <div class="collapsed">
        <span class="text-shadow">Comentarios</span>
        <?php echo Html::link('dc-admin/comentario/','Comentarios'); ?>
    </div>

    <?php if ( Session::get('nivel') < Grupo::AUTOR ): ?>
    <div class="collapsed">
        <span class="text-shadow">Enlaces</span>
        <?php echo Html::link('dc-admin/enlace/','Enlaces'); ?>
        <?php echo Html::link('dc-admin/enlace/agregar/','Agregar nuevo'); ?>
    </div>
    <?php endif; ?>

    <div class="collapsed">
        <span class="text-shadow">Usuarios</span>
        <?php echo Html::link('dc-admin/usuario/perfil/','Mi Cuenta'); ?>
        <?php if ( Session::get('nivel') < Grupo::COLABORADOR ): ?>
        <?php echo Html::link('dc-admin/usuario/','Usuarios'); ?>
        <?php echo Html::link('dc-admin/usuario/agregar/','Agregar'); ?>
        <?php endif; ?>
    </div>

    <?php if ( Session::get('nivel') < Grupo::AUTOR ): ?>    
    <div class="collapsed">
        <span class="text-shadow">Ajustes</span>
        <?php echo Html::link('dc-admin/ajustes/blog/','Blog'); ?>
        <?php echo Html::link('dc-admin/ajustes/publicaciones/','Publicaciones'); ?>
        <?php echo Html::link('dc-admin/ajustes/comentarios/','Comentarios'); ?>
    </div>
    <?php endif; ?>
</div>
<div class="break"></div>