<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Agregar Foto</h1></div>
    <?php echo ExtForm::openMultipart('', 'post', array('class'=>'post'), true); ?>
    <div class="left medium">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Metadata de la Foto</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Titulo</label>
                        <div>
                            <?php echo ExtForm::text('galeria.nombre', array('class'=>'small'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_apellido" class="desc">Descripción</label>
                        <div>
                            <?php echo ExtForm::text('galeria.descripcion', array('class'=>'large'), null, '', true, true); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="break"></div>
    </div>

    <div class="right medium">
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Datos Adicionales</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <div>
                            <label for="usuario_grupo_id" class="desc">Imagen a subir</label>
                            <?php echo ExtForm::file('fotos', array('class'=>'font-normal small')); ?>
                        </div>
                    </li>
                    <li>
                        <div>
                            <label for="usuario_registrado_at" class="desc">Fecha de creación</label>
                            <?php echo ExtForm::text('fecha', array('class'=>'font-normal fecha small', 'disabled' => 'disabled'), date("Y-m-d"), '', true, true); ?>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Subir Imagen',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>

        <div class="break"></div>
    </div>

    <div class="full">

        <div class="box ui-corner-all ui-widget-content" id="data-grid">
            <table class="data-grid" cellspacing="0">
                <thead class="ui-state-default ui-corner-tl ui-corner-tr">
                    <tr class="text-shadow">
                        <th class="columna-check">&nbsp</th>
                        <th class="columna-titulo">Nombre</th>
                        <th class="columna-autor font-center">Autor</th>
                        <th class="columna-fecha font-center">Fecha</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ( $fotos->total == 0)
                        print "<td colspan='4' class='strong font-large font-center'>Álbum Vacío</td>";
                    else
                    foreach ($fotos->items as $fila) { ?>

                    <?php $validKey = md5($fila->id.$ipKey.$expKey.'galeria'); ?>
                    <tr>
                        <td>&nbsp;</td>
                        <td class="">
                            <?php echo Html::img('dcm/galeria/'.$fila->ruta.$fila->nombre_ruta, null, "width='100px' height='80px'"); ?>
                            <div style="display:inline-block; width:60%; vertical-align:top">
                                <span class="strong post-titulo font-large"><?php echo $fila->nombre; ?></span>
                                <br/>
                                <span class="post-titulo font-normal"><?php echo $fila->descripcion; ?></span>
                                <div class="row-actions font-small">
                                    <span class="row-action-delete"><?php echo Html::link("dc-admin/galeria/eliminar_foto/$fila->id/key/$validKey/",'Eliminar');?></span>
                                </div>
                            </div>
                        </td>
                        <td class="font-small font-center"><?php echo $fila->login; ?></td>
                        <td class="font-small"><?php echo ExtDate::getHowLong($fila->fecha_creacion_at.' '.$fila->hora_creacion_at);?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php View::partial('paginate',false,array('objeto'=>$fotos, 'tipo'=>'dc-admin')); ?>
        </div>
    </div>

<!-- Alertas -->
<script type="text/javascript">
    var link_action;
    $('a','.row-action-delete').click(function(event){ event.preventDefault(); link_action = $(this).attr('href'); $('#eliminar-post').dialog('open'); });
    $(function() { $("#eliminar-post").dialog({ autoOpen: false, width: 400, height:155, modal: true, buttons: { 'Cancelar': function() { $(this).dialog('close'); } ,'Aceptar': function() { location.href = link_action; } } }); });
</script>
<div id="eliminar-post" title="Dailyscript - Web | App | Media" class="confirm-dialog">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseas borrar permantentemente esta foto?. </p>
</div>
<script type="text/javascript">
    $(function() {
        $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('tr-hover'); },function() {});
    });
 </script>
