<?php View::partial('mensaje');?>

<div class="contenido">
    <div class="full"><h1 class="text-shadow">Crear Album</h1></div>
    <?php echo ExtForm::open('', 'post', array('class'=>'post'), true); ?>
    <div class="left medium">
        <div class="box ui-corner-all ui-widget-content" id="contenido-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Metadata del Album</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <label for="usuario_nombre" class="desc">Nombre<span class="req">*</span></label>
                        <div>
                            <?php echo ExtForm::text('galeria.nombre', array('class'=>'small'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_apellido" class="desc">Descripción</label>
                        <div>
                            <?php echo ExtForm::text('galeria.descripcion', array('class'=>'large'), null, '', true, true); ?>
                        </div>
                    </li>
                    <li>
                        <label for="usuario_email" class="desc">Ruta Física</label>
                        <div>
                            <?php echo ExtForm::text('ruta', array('class'=>'medium email', 'readonly' => 'readonly'), 'img/dcm/galeria/', '', true, true); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="break"></div>
    </div>

    <div class="right medium">
        <div class="box ui-corner-all ui-widget-content" id="publicar-post">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Datos Adicionales</h3></div>
            <div class="box-contenido box-form">
                <ul>
                    <li>
                        <div>
                            <label for="usuario_grupo_id" class="desc">Tipo de usuario</label>
                            <?php
                            $data = array('ACTIVO' => 'Activo', 'INACTIVO' => 'Inactivo');
                            echo ExtForm::select('galeria.estado', $data, array('class'=>'font-normal lista full'), '-- Seleccione -- ', null, '', false, true); ?>
                        </div>
                    </li>
                    <li>
                        <div>
                            <label for="usuario_registrado_at" class="desc">Fecha de creación</label>
                            <?php echo ExtForm::text('fecha', array('class'=>'font-normal fecha small', 'disabled' => 'disabled'), date("Y-m-d"), '', true, true); ?>
                        </div>
                    </li>
                </ul>
                <!-- Botones -->
                <div class="box-botones">
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                    <div class="right small">
                        <span><?php echo ExtForm::submit('Crear Album',array('id'=>'enviarForm','name'=>'btn_crear')); ?></span>
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>

        <div class="break"></div>
    </div>

<!-- Alertas -->
<script type="text/javascript">
    var base = $('#ruta').val();
    $('#galeria_nombre').on('keyup', function(){
        var text = $(this).val();
        text = text.replace(/ /g,'_');
        $('#ruta').val(base+text.toLowerCase());
    });
    $(function() { $('tr','tbody').hover(function(){$(this).addClass('tr-hover'); },function(){$(this).removeClass('ui-state-highlight tr-hover'); },function() {});});

    function mensaje(div, mensaje, tipo){
        $('#' + div).html(mensaje);
        if (tipo == 'info') {
            $('#' + div).removeClass('err');
            $('#' + div).addClass('succ');
            $("input[type='submit']").removeAttr('disabled', 'disabled');
            $("input[type='submit']").removeClass('ui-button-disabled ui-state-disabled');
        } else if (tipo == 'warn') {
            //$('#' + div).css('color', 'orange'); pendiente
        } else {
            $('#' + div).removeClass('succ');
            $('#' + div).addClass('err');
            $("input[type='submit']").addClass('ui-button-disabled ui-state-disabled');
            $("input[type='submit']").attr('disabled', 'disabled');
        }
    }

    $('#usuario_mail').keyup(function(){
        mail = $(this).val();

        if ( mail.length > 10 && mail.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$') ) {
            $.post(
                '../checkEmail',
                {
                    email: mail
                },
                function(data){
                    if (data.status == 'OK') {
                        mensaje('err_usuario_mail', 'Disponible', 'info');
                    } else {
                        mensaje('err_usuario_mail', 'Este email ya esta asignado a un usuario');
                    }
                },
                'json'
            );
        } else {
            mensaje('err_usuario_mail', '');
        }
    });//    ^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$

    $('#usuario_login').keyup(function(){
        nick = $(this).val();

        if ( nick.length >= 4 ) {
            $.post(
                '../checkLogin',
                {
                    login: nick
                },
                function(data){
                    if (data.status == 'OK') {
                        mensaje('err_usuario_login', 'Disponible', 'info');
                    } else {
                        mensaje('err_usuario_login', 'Este nick ya esta asignado a un usuario');
                    }
                },
                'json'
            );
        } else {
            mensaje('err_usuario_login', '');
        }
    });

    $('#repasswd').keyup(function(){
        pass = $('#usuario_password').val();
        repass = $(this).val();

        if ( pass == repass ) {
            mensaje('err_repasswd', '', 'info');
        } else {
            mensaje('err_repasswd', 'Las contrase&ntilde;as no coinciden');
        }
    });

    $('form').submit(function(){
        var pass = $("input[type='password']").val();
        $("input[type='password']").val(hex_sha1(pass));
    });

 </script>
