<!-- Box borradores -->
<div class="box ui-corner-all ui-widget-content" id="borradores">
    <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr box-expandido" id="borradores-titulo">
        <h3 class="text-shadow">Borradores</h3><span class="box-icono ui-icon ui-icon-circle-triangle-s"></span>
    </div>
    <div class="box-contenido">
        <?php $borradores = Load::model('post')->filtrarPost(Post::BORRADOR, '', '', 'asc', 5); ?>
        <?php if(!$borradores) { ?>
            <p>Por el momento no hay borradores.</p>
        <?php } else { ?>
            <?php foreach($borradores as $fila): ?>
            <?php $validKey = md5($fila->id.$ipKey.$expKey.'post'); ?>
            <p><span class="link-titulo"><?php echo Html::link("dc-admin/post/editar/$fila->id/key/$validKey/", $fila->titulo); ?></span> <span class="link-fecha"><?php echo ExtDate::getDateSpecial($fila->fecha_publicacion); ?></span></p>
            <p><?php echo Truncar::digito($fila->resumen,70); ?></p>
            <?php endforeach; ?>
        <?php } ?>
        <div class="box-botones">
            <div class="right">
                <?php echo Html::link('dc-admin/post/listar/borrador/','Ver todos', array('class'=>'link_button')); ?>
            </div>
            <div class="clr"></div>
        </div>
    </div>
</div>
<div class="break"></div>