<!-- Box quickpress -->
<div class="box ui-corner-all ui-widget-content" id="quickpress">
    <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr box-expandido" id="quickpress-titulo">
        <h3 class="text-shadow">Quickpress</h3><span class="box-icono ui-icon ui-icon-circle-triangle-s"></span>
    </div>
    <div class="box-contenido box-form">
        <?php echo ExtForm::open('dc-admin/post/agregar/', 'post', array('id'=>'formulario', 'name'=>'formulario','class'=>'js-remote','data-div'=>'mensaje-principal'), true); ?>
            <ul>
                <li>
                    <label for="post_titulo" class="desc">Título<span class="req">*</span></label>
                    <div>
                        <?php echo ExtForm::text('post.titulo', array('class'=>'full'), null, '', true, true); ?>
                    </div>
                </li>
                <li>
                    <label for="post_contenido" class="desc">Contenido<span class="req">*</span></label>
                    <div>
                        <?php echo ExtForm::textarea('post.contenido', array('class'=>'tinymce small'), null, '', 0, false, true); ?>
                    </div>
                </li>
                <li>
                    <label for="post_etiqueta" class="desc">Etiquetas</label>
                    <div>
                        <?php echo ExtForm::text('etiquetas', array('class'=>'full'), null, 'Pueden estar separadas por comas.', false, true); ?>
                    </div>
                    <div>
                        <?php echo ExtForm::hidden('post.quickpress','', 'quickpress');?>
                    </div>
                    <div>
                        <?php echo ExtForm::hidden('post.estado','', '');?>
                    </div>
                    <div>
                        <?php echo SecurityKey::generateKey(); ?>
                    </div>
                </li>
            </ul>
            <div class="box-botones">
                <script type="text/javascript">
                    <?php $publicado = (Session::get('grupo_id') == Grupo::COLABORADOR) ? Post::PENDIENTE : Post::PUBLICADO; ?>
                    $(function() {$('#btn_borrador').click(function(){$("input[name=post[estado]]").attr('value','<?php echo Post::BORRADOR; ?>');});});                    
                    $(function() {$('#btn_publicar').click(function(){$("input[name=post[estado]]").attr('value','<?php echo $publicado; ?>');});});
                 </script>
                <div class="left medium">
                    <span style="padding-right: 10px;"><?php echo ExtForm::submit('Borrador',array('id'=>'btn_borrador','name'=>'btn_borrador','class'=>'text_shadow')); ?></span>
                    <span><?php echo ExtForm::button('Limpiar',array('id'=>'limpiar','class'=>'text_shadow')); ?></span>
                </div>
                <div class="right medium">
                    <span><?php echo ExtForm::submit('Publicar',array('id'=>'btn_publicar','name'=>'btn_publicar','class'=>'text_shadow')); ?></span>
                </div>
                <div class="clr"></div>
            </div>
        <?php echo Form::close(); ?>
        <?php View::partial('tiny_mce/quickpress'); ?>
    </div>
</div>
<div class="break"></div>
<script type="text/javascript">$(function() {$('#limpiar').click(function(){document.getElementById('formulario').reset();limpiar_err();});});</script>