<?php View::partial('mensaje');?>

<div class="contenido">

    <div class="left medium"><h1 class="text-shadow">Página de administración</h1></div>    
    <div class="clr"></div>

    <div class="left medium">
        
        <div class="box ui-corner-all ui-widget-content" id="actualmente">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr box-expandido" id="actualmente-titulo">
                <h3 class="text-shadow">Actualmente</h3><span class="box-icono ui-icon ui-icon-circle-triangle-s" style="margin: -21px 10px 0px 95%"></span>
            </div>

            <?php if ( Session::get('nivel') < Grupo::COLABORADOR ): ?>
            <div class="box-contenido">
                <div class="left medium">
                    <div class="box-subtitulo"><h3 class="text-shadow">Contenido</h3></div>
                    <table class="box-table" cellspacing="3" cellpadding="3">
                        <tr><td class="box-contador" id="total_post"><?php echo Html::link('dc-admin/post/',$total_post); ?></td><td class="box-info"><?php echo Html::link('dc-admin/post/',$detalle_post); ?></td></tr>
                        <tr><td class="box-contador" id="total_borradores"><?php echo Html::link('dc-admin/post/listar/borrador/',$total_borradores); ?></td><td class="box-info"><?php echo Html::link('dc-admin/post/listar/borrador/',$detalle_borrador); ?></td></tr>
                        <tr><td class="box-contador" id="total_categorias"><?php echo Html::link('dc-admin/categoria/',$total_categorias); ?></td><td class="box-info"><?php echo Html::link('dc-admin/categoria/',$detalle_categoria); ?></td></tr>
                        <tr><td class="box-contador" id="total_etiquetas"><?php echo Html::link('dc-admin/etiqueta/',$total_etiquetas); ?></td><td class="box-info"><?php echo Html::link('dc-admin/etiqueta/',$detalle_etiqueta); ?></td></tr>
                    </table>
                </div>
            <?php elseif ( Session::get('nivel') == Grupo::COLABORADOR ): ?>
            <div class="box-contenido">
                <div class="left medium">
                    <div class="box-subtitulo"><h3 class="text-shadow">Contenido</h3></div>
                    <table class="box-table" cellspacing="3" cellpadding="3">
                        <tr>
                            <td class="box-contador" id="total_post"><?php echo $total_post; ?></td>
                            <td class="box-info"><?php echo $detalle_post; ?></td>
                        </tr>
                        <tr>
                            <td class="box-contador" id="total_borradores"><?php echo $total_borradores; ?></td>
                            <td class="box-info"><?php echo $detalle_borrador; ?></td>
                        </tr>
                        <tr>
                            <td class="box-contador" id="total_categorias"><?php echo $total_categorias; ?></td>
                            <td class="box-info"><?php echo $detalle_categoria; ?></td>
                        </tr>
                        <tr>
                            <td class="box-contador" id="total_etiquetas"><?php echo $total_etiquetas; ?></td>
                            <td class="box-info"><?php echo $detalle_etiqueta; ?></td>
                        </tr>
                    </table>
                </div>
            <?php endif; ?>

                <div class="right medium">
                    <div class="box-subtitulo"><h3 class="text-shadow">Comentarios</h3></div>
                    <table class="box-table" cellspacing="3" cellpadding="3">
                        <tr><td class="box-contador">0</td><td>Total</td></tr>
                        <tr><td class="box-contador" id="total_comentarios"><?php echo $total_comentarios; ?></td><td class="box-aprobados"><?php echo Html::link('dc-admin/comentario/',$detalle_comentario, array('class'=>'font-medium')); ?></td></tr>
                        <tr><td class="box-contador" id="total_pendientes"><?php echo $total_pendientes; ?></td><td class="box-pendientes"><?php echo Html::link('dc-admin/comentario/listar/pendiente/',$detalle_pendiente, array('class'=>'font-medium')); ?></td></tr>
                        <tr><td class="box-contador" id="total_spam"><?php echo $total_spam; ?></td><td class="box-spam"><?php echo Html::link('dc-admin/comentario/listar/spam/',$detalle_spam, array('class'=>'font-medium')); ?></td></tr>
                    </table>
                </div>
                <div class="clr"></div>
                <div class="full">
                    <div class="box-subtitulo" style="text-align: center;"><h3 class="text-shadow"><?php echo APP_NAME; ?></h3></div>
                </div>
            </div>
        </div>

        <div class="break"></div>

        <?php if ( Session::get('nivel') < Grupo::COLABORADOR ): ?>
        <?php View::partial('admin/boxes/comentarios', false, array('ipKey'=>$ipKey,'expKey'=>$expKey)); ?>
        <?php View::partial('admin/boxes/borradores', false, array('ipKey'=>$ipKey,'expKey'=>$expKey)); ?>
        <?php endif; ?>
    </div>

    
    <div class="right medium">
        <?php if ( Session::get('nivel') == Grupo::COLABORADOR ): ?>
        <?php View::partial('admin/boxes/comentarios', false, array('ipKey'=>$ipKey,'expKey'=>$expKey)); ?>
        <?php elseif ( Session::get('nivel') < Grupo::COLABORADOR ): ?>
        <?php View::partial('admin/boxes/quickpress', false, array('ipKey'=>$ipKey,'expKey'=>$expKey)); ?>
        <?php endif; ?>
    </div>
    <div class="clr"></div>   
</div>

<?php echo Tag::js('jquery/jquery.cookie'); ?>
<?php echo Tag::js('boxes'); ?>
