<?php Tag::css('jquery-ui/jquery.ui.all');?>
<?php Tag::css('formulario');?>
<?php echo Tag::js('jquery/jquery-ui.min');?>
<?php echo Tag::js('formulario');?>
<div class="contenido">
    <!-- Mensaje -->
    <div class="contenedor-mensaje">
        <div class="mensaje">
            <?php View::content(); echo "\r\n"; ?>
        </div>
    </div>
    <div class="left">
        <div class="form">
            <?php echo ExtForm::open('contacto/', 'post', array('id'=>'formulario', 'name'=>'formulario'), true); ?>
            <ul>
                <li>
                    <div>
                        <?php echo ExtForm::text('contacto.nombre', array('class'=>'alfabetico full'), null, 'Nombre', true, true); ?>
                    </div>
                </li>
                <li>
                    <div>
                        <?php echo ExtForm::text('contacto.email', array('class'=>'email full'), null, 'Email', true, true); ?>
                    </div>
                </li>
                <li>
                    <div>
                        <?php echo ExtForm::text('contacto.web', array('class'=>'email full'), null, 'Web', false, true); ?>
                    </div>
                </li>
                <li>
                    <div>
                        <?php echo ExtForm::textarea('contacto.mensaje', array('class'=>'texto medium', 'maxlength'=>'1500'), null, 'Mensaje', 1500, true, true); ?>
                    </div>
                </li>
                <li>
                    <div>
                        <?php View::partial('blog/comentarios/recaptcha'); ?>
                    </div>
                </li>
            </ul>
            <div class="botones">
                <?php echo ExtForm::submitImage('pagina/enviar.png', array('id' => 'send')); ?>
            </div>
            <?php echo Form::close(); ?>
            <div class="clr"></div>
        </div>
    </div>

    <div class="clr"></div>
</div>