<!-- Captcha -->
<?php $app = Api::recaptcha(); ?>
<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
<div id="recaptcha" style="width: 450px; margin: auto;"></div>
<script type="text/javascript">
Recaptcha.create('<?php echo $app['public_key'] ?>', 'recaptcha', {
 theme: "clean",
 lang: "es",
 callback: Recaptcha.focus_response_field
});
</script>
<!-- Captcha -->
