        <!-- Redes Sociales -->
        <div class="box ui-corner-all ui-widget-content">
            <div class="box-titulo ui-state-default ui-corner-tl ui-corner-tr"><h3 class="text-shadow">Redes Sociales</h3></div>
            <div class="box-contenido box-form">
                <ul>
                <?php View::partial('redes_sociales/twitter/cuenta'); ?>
                <?php View::partial('redes_sociales/facebook/cuenta'); ?>
                </ul>
            </div>
        </div>
        <div class="break"></div>
        <!-- Redes Sociales -->